{% set name = "ndsplines" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndsplines-{{ version }}.tar.gz
  sha256: 39f1b7f0d7e0f99bc45099b87716abd62d5e5b07820680e1adb8d9188ef352b9

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=45
    - setuptools-scm
    - cython
    - numpy  # [py<312]
    - numpy >=1.26.0  # [py>=312]
    - pip
  run:
    - python
    - scipy

test:
  imports:
    - ndsplines
  commands:
    - python -c "import ndsplines; ndsplines.get_impl() == 'cython'"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kb-press/ndsplines
  summary: Multi-dimensional splines
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ndsplines.readthedocs.io

extra:
  recipe-maintainers:
    - ixjlyons
    - danschef
